# gowinproc configuration example
# Copy this file to config.yaml and modify as needed

# Server configuration
server:
  host: localhost
  port: 8080
  grpc_port: 50051
  read_timeout: 30s
  write_timeout: 30s

# Secrets management configuration
secrets:
  mode: standalone  # "standalone" or "cloudflare"

  # Uncomment for Cloudflare mode
  # cloudflare:
  #   worker_url: https://your-auth-worker.workers.dev
  #   private_key_path: ./keys/client_private.pem

# GitHub integration configuration
github:
  mode: standalone  # "standalone" or "cloudflare"

  # Uncomment for Cloudflare mode
  # cloudflare:
  #   worker_url: https://your-github-webhook-worker.workers.dev
  #   private_key_path: ./keys/client_private.pem

  # Update mode configuration
  update_mode:
    # Polling mode - polls github-webhook-worker for version updates
    polling:
      enabled: false  # Set to true for Cloudflare polling mode
      interval: 5m

    # Webhook mode - receives updates via webhook (requires tunnel)
    # webhook:
    #   enabled: false
    #   path: /webhook/cloudflare

# Cloudflare Tunnel configuration (optional - for webhook reception)
# Requires cloudflared to be installed
# tunnel:
#   enabled: false
#   port: 8080        # Port where gowinproc is listening
#   protocol: http2   # "http2" or "quic"

# Managed processes
processes:
  - name: example-service
    repository: owner/repo-name  # GitHub repository for updates
    binary_path: ./binaries/example-service/latest/example-service.exe
    args:
      - --port
      - "9000"
    env:
      SERVICE_NAME: example-service
      LOG_LEVEL: info
    work_dir: ./processes/example-service
    port: 9000
    health_check:
      enabled: true
      endpoint: http://localhost:9000/health
      interval: 30s
      timeout: 5s
      retries: 3
    auto_restart: true
    max_instances: 2

  # Add more processes as needed
  # - name: another-service
  #   repository: owner/another-repo
  #   binary_path: ./binaries/another-service/latest/another-service.exe
  #   port: 9001
  #   auto_restart: true
  #   max_instances: 1
