// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: tunnel_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelService_GetRegistry_FullMethodName  = "/tunnel.TunnelService/GetRegistry"
	TunnelService_InvokeMethod_FullMethodName = "/tunnel.TunnelService/InvokeMethod"
)

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TunnelService provides gRPC-Web endpoints for tunnel management
type TunnelServiceClient interface {
	// GetRegistry returns the registry of available processes and services
	GetRegistry(ctx context.Context, in *TunnelRegistryRequest, opts ...grpc.CallOption) (*TunnelRegistryResponse, error)
	// InvokeMethod invokes a gRPC method on a managed process
	InvokeMethod(ctx context.Context, in *TunnelInvokeRequest, opts ...grpc.CallOption) (*TunnelInvokeResponse, error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) GetRegistry(ctx context.Context, in *TunnelRegistryRequest, opts ...grpc.CallOption) (*TunnelRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelRegistryResponse)
	err := c.cc.Invoke(ctx, TunnelService_GetRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelServiceClient) InvokeMethod(ctx context.Context, in *TunnelInvokeRequest, opts ...grpc.CallOption) (*TunnelInvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelInvokeResponse)
	err := c.cc.Invoke(ctx, TunnelService_InvokeMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility.
//
// TunnelService provides gRPC-Web endpoints for tunnel management
type TunnelServiceServer interface {
	// GetRegistry returns the registry of available processes and services
	GetRegistry(context.Context, *TunnelRegistryRequest) (*TunnelRegistryResponse, error)
	// InvokeMethod invokes a gRPC method on a managed process
	InvokeMethod(context.Context, *TunnelInvokeRequest) (*TunnelInvokeResponse, error)
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelServiceServer struct{}

func (UnimplementedTunnelServiceServer) GetRegistry(context.Context, *TunnelRegistryRequest) (*TunnelRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegistry not implemented")
}
func (UnimplementedTunnelServiceServer) InvokeMethod(context.Context, *TunnelInvokeRequest) (*TunnelInvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeMethod not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}
func (UnimplementedTunnelServiceServer) testEmbeddedByValue()                       {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	// If the following call pancis, it indicates UnimplementedTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_GetRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).GetRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelService_GetRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).GetRegistry(ctx, req.(*TunnelRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelService_InvokeMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelServiceServer).InvokeMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelService_InvokeMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelServiceServer).InvokeMethod(ctx, req.(*TunnelInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegistry",
			Handler:    _TunnelService_GetRegistry_Handler,
		},
		{
			MethodName: "InvokeMethod",
			Handler:    _TunnelService_InvokeMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tunnel_service.proto",
}
