// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tunnel_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelRegistryRequest is an empty request for getting the registry
type TunnelRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelRegistryRequest) Reset() {
	*x = TunnelRegistryRequest{}
	mi := &file_tunnel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRegistryRequest) ProtoMessage() {}

func (x *TunnelRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRegistryRequest.ProtoReflect.Descriptor instead.
func (*TunnelRegistryRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{0}
}

// TunnelRegistryResponse contains the registry information
type TunnelRegistryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProxyBaseUrl       string                 `protobuf:"bytes,1,opt,name=proxy_base_url,json=proxyBaseUrl,proto3" json:"proxy_base_url,omitempty"`
	AvailableProcesses []*TunnelProcessInfo   `protobuf:"bytes,2,rep,name=available_processes,json=availableProcesses,proto3" json:"available_processes,omitempty"`
	Timestamp          string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TunnelRegistryResponse) Reset() {
	*x = TunnelRegistryResponse{}
	mi := &file_tunnel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRegistryResponse) ProtoMessage() {}

func (x *TunnelRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRegistryResponse.ProtoReflect.Descriptor instead.
func (*TunnelRegistryResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelRegistryResponse) GetProxyBaseUrl() string {
	if x != nil {
		return x.ProxyBaseUrl
	}
	return ""
}

func (x *TunnelRegistryResponse) GetAvailableProcesses() []*TunnelProcessInfo {
	if x != nil {
		return x.AvailableProcesses
	}
	return nil
}

func (x *TunnelRegistryResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// TunnelProcessInfo represents information about a managed process
type TunnelProcessInfo struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                    `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status        string                    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Instances     int32                     `protobuf:"varint,4,opt,name=instances,proto3" json:"instances,omitempty"`
	ProxyPath     string                    `protobuf:"bytes,5,opt,name=proxy_path,json=proxyPath,proto3" json:"proxy_path,omitempty"`
	Repository    string                    `protobuf:"bytes,6,opt,name=repository,proto3" json:"repository,omitempty"`
	CurrentPorts  []int32                   `protobuf:"varint,7,rep,packed,name=current_ports,json=currentPorts,proto3" json:"current_ports,omitempty"`
	Services      []*ServiceDetail          `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	Messages      map[string]*MessageDetail `protobuf:"bytes,9,rep,name=messages,proto3" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelProcessInfo) Reset() {
	*x = TunnelProcessInfo{}
	mi := &file_tunnel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelProcessInfo) ProtoMessage() {}

func (x *TunnelProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelProcessInfo.ProtoReflect.Descriptor instead.
func (*TunnelProcessInfo) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelProcessInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TunnelProcessInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TunnelProcessInfo) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *TunnelProcessInfo) GetProxyPath() string {
	if x != nil {
		return x.ProxyPath
	}
	return ""
}

func (x *TunnelProcessInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *TunnelProcessInfo) GetCurrentPorts() []int32 {
	if x != nil {
		return x.CurrentPorts
	}
	return nil
}

func (x *TunnelProcessInfo) GetServices() []*ServiceDetail {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *TunnelProcessInfo) GetMessages() map[string]*MessageDetail {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ServiceDetail represents a gRPC service with its methods
type ServiceDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Methods       []*MethodDetail        `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDetail) Reset() {
	*x = ServiceDetail{}
	mi := &file_tunnel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDetail) ProtoMessage() {}

func (x *ServiceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDetail.ProtoReflect.Descriptor instead.
func (*ServiceDetail) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDetail) GetMethods() []*MethodDetail {
	if x != nil {
		return x.Methods
	}
	return nil
}

// MethodDetail represents a gRPC method
type MethodDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InputType     string                 `protobuf:"bytes,2,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	OutputType    string                 `protobuf:"bytes,3,opt,name=output_type,json=outputType,proto3" json:"output_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodDetail) Reset() {
	*x = MethodDetail{}
	mi := &file_tunnel_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodDetail) ProtoMessage() {}

func (x *MethodDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodDetail.ProtoReflect.Descriptor instead.
func (*MethodDetail) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{4}
}

func (x *MethodDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodDetail) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *MethodDetail) GetOutputType() string {
	if x != nil {
		return x.OutputType
	}
	return ""
}

// MessageDetail represents a protobuf message schema
type MessageDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*FieldDetail         `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDetail) Reset() {
	*x = MessageDetail{}
	mi := &file_tunnel_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDetail) ProtoMessage() {}

func (x *MessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDetail.ProtoReflect.Descriptor instead.
func (*MessageDetail) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{5}
}

func (x *MessageDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageDetail) GetFields() []*FieldDetail {
	if x != nil {
		return x.Fields
	}
	return nil
}

// FieldDetail represents a field in a message
type FieldDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Repeated      bool                   `protobuf:"varint,3,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Number        int32                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Optional      bool                   `protobuf:"varint,5,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDetail) Reset() {
	*x = FieldDetail{}
	mi := &file_tunnel_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDetail) ProtoMessage() {}

func (x *FieldDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDetail.ProtoReflect.Descriptor instead.
func (*FieldDetail) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{6}
}

func (x *FieldDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldDetail) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

func (x *FieldDetail) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *FieldDetail) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

// TunnelInvokeRequest represents a gRPC method invocation request
type TunnelInvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       string                 `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"` // Process name (e.g., "db_service_local")
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // Service name (e.g., "db_service.db_ChiikiMasterService")
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`   // Method name (e.g., "List")
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`       // Request data as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelInvokeRequest) Reset() {
	*x = TunnelInvokeRequest{}
	mi := &file_tunnel_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInvokeRequest) ProtoMessage() {}

func (x *TunnelInvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInvokeRequest.ProtoReflect.Descriptor instead.
func (*TunnelInvokeRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{7}
}

func (x *TunnelInvokeRequest) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *TunnelInvokeRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TunnelInvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TunnelInvokeRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// TunnelInvokeResponse represents a gRPC method invocation response
type TunnelInvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Response data as JSON string
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelInvokeResponse) Reset() {
	*x = TunnelInvokeResponse{}
	mi := &file_tunnel_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInvokeResponse) ProtoMessage() {}

func (x *TunnelInvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInvokeResponse.ProtoReflect.Descriptor instead.
func (*TunnelInvokeResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_service_proto_rawDescGZIP(), []int{8}
}

func (x *TunnelInvokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TunnelInvokeResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TunnelInvokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tunnel_service_proto protoreflect.FileDescriptor

const file_tunnel_service_proto_rawDesc = "" +
	"\n" +
	"\x14tunnel_service.proto\x12\x06tunnel\"\x17\n" +
	"\x15TunnelRegistryRequest\"\xa8\x01\n" +
	"\x16TunnelRegistryResponse\x12$\n" +
	"\x0eproxy_base_url\x18\x01 \x01(\tR\fproxyBaseUrl\x12J\n" +
	"\x13available_processes\x18\x02 \x03(\v2\x19.tunnel.TunnelProcessInfoR\x12availableProcesses\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xb0\x03\n" +
	"\x11TunnelProcessInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tinstances\x18\x04 \x01(\x05R\tinstances\x12\x1d\n" +
	"\n" +
	"proxy_path\x18\x05 \x01(\tR\tproxyPath\x12\x1e\n" +
	"\n" +
	"repository\x18\x06 \x01(\tR\n" +
	"repository\x12#\n" +
	"\rcurrent_ports\x18\a \x03(\x05R\fcurrentPorts\x121\n" +
	"\bservices\x18\b \x03(\v2\x15.tunnel.ServiceDetailR\bservices\x12C\n" +
	"\bmessages\x18\t \x03(\v2'.tunnel.TunnelProcessInfo.MessagesEntryR\bmessages\x1aR\n" +
	"\rMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.tunnel.MessageDetailR\x05value:\x028\x01\"S\n" +
	"\rServiceDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\amethods\x18\x02 \x03(\v2\x14.tunnel.MethodDetailR\amethods\"b\n" +
	"\fMethodDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"input_type\x18\x02 \x01(\tR\tinputType\x12\x1f\n" +
	"\voutput_type\x18\x03 \x01(\tR\n" +
	"outputType\"P\n" +
	"\rMessageDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06fields\x18\x02 \x03(\v2\x13.tunnel.FieldDetailR\x06fields\"\x85\x01\n" +
	"\vFieldDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brepeated\x18\x03 \x01(\bR\brepeated\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12\x1a\n" +
	"\boptional\x18\x05 \x01(\bR\boptional\"u\n" +
	"\x13TunnelInvokeRequest\x12\x18\n" +
	"\aprocess\x18\x01 \x01(\tR\aprocess\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"Z\n" +
	"\x14TunnelInvokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xa8\x01\n" +
	"\rTunnelService\x12L\n" +
	"\vGetRegistry\x12\x1d.tunnel.TunnelRegistryRequest\x1a\x1e.tunnel.TunnelRegistryResponse\x12I\n" +
	"\fInvokeMethod\x12\x1b.tunnel.TunnelInvokeRequest\x1a\x1c.tunnel.TunnelInvokeResponseB?Z=github.com/yhonda-ohishi-pub-dev/gowinproc/src/internal/protob\x06proto3"

var (
	file_tunnel_service_proto_rawDescOnce sync.Once
	file_tunnel_service_proto_rawDescData []byte
)

func file_tunnel_service_proto_rawDescGZIP() []byte {
	file_tunnel_service_proto_rawDescOnce.Do(func() {
		file_tunnel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_service_proto_rawDesc), len(file_tunnel_service_proto_rawDesc)))
	})
	return file_tunnel_service_proto_rawDescData
}

var file_tunnel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tunnel_service_proto_goTypes = []any{
	(*TunnelRegistryRequest)(nil),  // 0: tunnel.TunnelRegistryRequest
	(*TunnelRegistryResponse)(nil), // 1: tunnel.TunnelRegistryResponse
	(*TunnelProcessInfo)(nil),      // 2: tunnel.TunnelProcessInfo
	(*ServiceDetail)(nil),          // 3: tunnel.ServiceDetail
	(*MethodDetail)(nil),           // 4: tunnel.MethodDetail
	(*MessageDetail)(nil),          // 5: tunnel.MessageDetail
	(*FieldDetail)(nil),            // 6: tunnel.FieldDetail
	(*TunnelInvokeRequest)(nil),    // 7: tunnel.TunnelInvokeRequest
	(*TunnelInvokeResponse)(nil),   // 8: tunnel.TunnelInvokeResponse
	nil,                            // 9: tunnel.TunnelProcessInfo.MessagesEntry
}
var file_tunnel_service_proto_depIdxs = []int32{
	2, // 0: tunnel.TunnelRegistryResponse.available_processes:type_name -> tunnel.TunnelProcessInfo
	3, // 1: tunnel.TunnelProcessInfo.services:type_name -> tunnel.ServiceDetail
	9, // 2: tunnel.TunnelProcessInfo.messages:type_name -> tunnel.TunnelProcessInfo.MessagesEntry
	4, // 3: tunnel.ServiceDetail.methods:type_name -> tunnel.MethodDetail
	6, // 4: tunnel.MessageDetail.fields:type_name -> tunnel.FieldDetail
	5, // 5: tunnel.TunnelProcessInfo.MessagesEntry.value:type_name -> tunnel.MessageDetail
	0, // 6: tunnel.TunnelService.GetRegistry:input_type -> tunnel.TunnelRegistryRequest
	7, // 7: tunnel.TunnelService.InvokeMethod:input_type -> tunnel.TunnelInvokeRequest
	1, // 8: tunnel.TunnelService.GetRegistry:output_type -> tunnel.TunnelRegistryResponse
	8, // 9: tunnel.TunnelService.InvokeMethod:output_type -> tunnel.TunnelInvokeResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tunnel_service_proto_init() }
func file_tunnel_service_proto_init() {
	if File_tunnel_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_service_proto_rawDesc), len(file_tunnel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnel_service_proto_goTypes,
		DependencyIndexes: file_tunnel_service_proto_depIdxs,
		MessageInfos:      file_tunnel_service_proto_msgTypes,
	}.Build()
	File_tunnel_service_proto = out.File
	file_tunnel_service_proto_goTypes = nil
	file_tunnel_service_proto_depIdxs = nil
}
